In [1]:
import numpy as np
import tensorflow as tf

In [2]:
def formula(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x


function_that_uses_a_graph = tf.function(formula)

x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = formula(x1, y1, b1).numpy()
tf_function_value = function_that_uses_a_graph(x1, y1, b1).numpy()

assert (orig_value == tf_function_value)

In [3]:
print(x1.shape)

(1, 2)


In [13]:
def formula(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x


@tf.function
def function_that_uses_a_graph(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x


x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = formula(x1, y1, b1).numpy()
tf_function_value = function_that_uses_a_graph(x1, y1, b1).numpy()

assert (orig_value == tf_function_value)

In [14]:
formula(x1, y1, b1).numpy()

array([[12.]], dtype=float32)

In [15]:
def f(x):
    return 1 / x ** 2


x = tf.Variable(2.0)
with tf.GradientTape() as tape:
    y = f(x)
    dydx = tape.gradient(y, x)
    print(dydx)

tf.Tensor(-0.25, shape=(), dtype=float32)


In [27]:
class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(5.0)
        self.b = tf.Variable(5.0)

    def __call__(self, x):
        return self.w * x + self.b


simple_module = SimpleModule(name="simple")
print(simple_module(tf.constant(5.0)))

tf.Tensor(30.0, shape=(), dtype=float32)


In [28]:
class DenseLayer(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([in_features, out_features]), name="w"
        )
        self.b = tf.Variable(tf.zeros([out_features]), name="b")

    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)


class NN(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.layer_1 = DenseLayer(in_features=3, out_features=3)
    self.layer_2 = DenseLayer(in_features=3, out_features=1)

  def __call__(self, x):
    x = self.layer_1(x)
    return self.layer_2(x)


nn = NN(name="neural_network")
print("Results: ", nn(tf.constant([[2.0, 2.0, 2.0]])))

Results:  tf.Tensor([[0.9445277]], shape=(1, 1), dtype=float32)


In [34]:
w = tf.Variable(tf.random.normal([3, 1]))
w

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.3511289],
       [0.6989095],
       [1.6882557]], dtype=float32)>

In [38]:
b = tf.Variable(tf.zeros([3]))
x = tf.constant([[2.0, 2.0, 2.0]])
y = tf.matmul(x, w) + b
y

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[7.4765882, 7.4765882, 7.4765882]], dtype=float32)>

In [33]:
tf.nn.relu(y)

<tf.Tensor: shape=(), dtype=float32, numpy=0.25>