In [3]:
import numpy as np

first_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a = np.zeros((3, 3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
a = np.random.randint(1, 10, (5, 5))
a

array([[1, 8, 1, 2, 6],
       [2, 4, 3, 7, 2],
       [1, 1, 9, 4, 1],
       [9, 8, 1, 3, 9],
       [3, 7, 8, 3, 8]])

In [11]:
a = np.random.random((4, 4))
a

array([[0.96036801, 0.6877687 , 0.35857218, 0.15913554],
       [0.95627957, 0.10539487, 0.90847877, 0.42784964],
       [0.58754538, 0.63459023, 0.74631406, 0.56970999],
       [0.11340928, 0.58219818, 0.1307411 , 0.71439416]])

In [17]:
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
addition = a + b
subtraction = a - b
multiplication = a * b
a, b, addition, subtraction, multiplication

(array([1, 6, 7, 8, 4]),
 array([6, 5, 3, 7, 4]),
 array([ 7, 11, 10, 15,  8]),
 array([-5,  1,  4,  1,  0]),
 array([ 6, 30, 21, 56, 16]))

In [20]:
# a = np.random.randint(1, 10, 7)
# b = np.random.randint(1, 10, 7)
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([4, 5, 4, 3, 2, 1, 2])
np.dot(a, b)

68

In [21]:
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 3))
np.dot(a, b)

array([[43, 55, 25],
       [25, 32, 14]])

In [22]:
a = np.random.randint(1, 10, (3, 3))
np.linalg.inv(a)

array([[-0.03076923, -0.03076923,  0.13846154],
       [ 0.47692308, -0.52307692,  0.35384615],
       [-0.33846154,  0.66153846, -0.47692308]])

In [23]:
a = np.random.random((3, 3))
a, a.T

(array([[0.10049493, 0.70380327, 0.93761799],
        [0.30536023, 0.00372757, 0.08445735],
        [0.57002573, 0.92305428, 0.77816962]]),
 array([[0.10049493, 0.30536023, 0.57002573],
        [0.70380327, 0.00372757, 0.92305428],
        [0.93761799, 0.08445735, 0.77816962]]))

In [ ]:
a = np.random.randint(1, 10, (3, 3))
